#18 Change structure of root module

diff --git a/bin/set_tf_alias b/bin/set_tf_alias
--- a/bin/set_tf_alias
+++ b/bin/set_tf_alias
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
 # Check if the alias already exists in the .bash_profile
-grep -q 'alias tf="terraform"' -/.bash_profile
+grep -q 'alias tf="terraform"' ~/.bash_profile
 
-# $? is a special vvariable in bash that holds the exit status of the last command executed
-if [ $? -ne - ]; then
+# $? is a special variable in bash that holds the exit status of the last command executed
+if [ $? -ne 0 ]; then
     # if the alias does not exist, append it 
     echo 'alias tf="terraform"' >> ~/.bash_profile
     echo "Alias added successfully"
@@ -13,3 +13,5 @@ else
     echo "Alias already exists in .bash_profile."
 fi
 
+# Optional: source the .bash_profile to make the alias available immediately
+source ~/.bash_profile
